# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.16.0'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm run cypress:run:yvytu
  displayName: 'npm install and build'
  
- task: CmdLine@2
  inputs:
    script: 'npm run generate:report'

- task: CmdLine@2
  inputs:
    script: 'npm run generate:lighthouse:report'

