# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.16.0'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm run cypress:run:yvytu
  displayName: 'npm install and build'
  
- script: |
    npm run generate:report
  displayName: 'Run Generate Report'

- script: |
    npm run generate:lighthouse:report
  displayName: 'Run lighthouse report'

- script: |
    node junit-report.js
  displayName: 'Run Generate JUNIT Report'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'reports/test_result.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/results'
    failTaskOnFailedTests: true